name: BossBarManager
version: 1.1.0
main: dev.gnils.bossbarmanager.BoosterBossBarPlugin
api-version: 1.21
depend: [PlaceholderAPI]
author: gnils
commands:
  bbm:
    description: The main command for the plugin
    usage: /bbm [reload]
    permission: bossbarmanager.use
permissions:
  bossbarmanager.use:
    description: "Allow using the /bbm command."
    default: op
  bossbarmanager.reload:
    description: "Allow using the /bbm reload command."
    default: op